### ISSUE TITLE
Portfolio feedback!

### ISSUE THREAD

**Issue by jabyess** [isaberg/isaberg.github.io#1]
This looks great, honestly. 

You've got everything working responsively. It'll be interesting to see how that works when you add more content, like links or images or whatever.

Your code is clean and well formatted, and the css styling is nice. The HTML especially - you used semantic HTML naming! Perfect. 

No JS code yet, but I'm sure you'll add some!

**Comment by isaberg** [comment]
@jabyess  - check out my newest implementation!
